#ifndef PNTR_APP_SOUNDFONT_H__
#define PNTR_APP_SOUNDFONT_H__

// HEADER

#endif // PNTR_APP_SOUNDFONT_H__

#ifdef PNTR_APP_SOUNDFONT_IMPLEMENTATION
#ifndef PNTR_APP_SOUNDFONT_IMPLEMENTATION_ONCE
#define PNTR_APP_SOUNDFONT_IMPLEMENTATION_ONCE

// IMPLEMENTATION

#endif // PNTR_APP_SOUNDFONT_IMPLEMENTATION_ONCE
#endif // PNTR_APP_SOUNDFONT_IMPLEMENTATION
